Network:
  physical_batch_size: 16
#  physical_batch_size: 5
  lr: 2e-4
#  lr: 1e-3
#  weight_decay: 5e-4
  amsgrad: False
  weight_decay: 0
#  num_epochs: 150
  num_epochs: 80
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
DP_checkpoint_name: DP_checkpoint.tar
trained_model_name: trained_model.pth

# changeable items:
file_path: /home/soroosh/Documents/datasets/XRay/
target_dir: /home/soroosh/Documents/Repositories_target_files/privacydomain/
display_stats_freq: 1 # valid freq is equal to this

DP:
#  epsilon: 3
  epsilon: 4
#  epsilon: 6
#  epsilon: 8
#  epsilon: 10
#  delta: 1e-6  # [for full UKA]
#  delta: 7e-6  # [for full chexpert]
  delta: 1e-5  # [for full padchest & CXR14]
  max_grad_norm: 1.5 # this has a direct relationship with controlling the sensitivity
#  noise_multiplier: 0.2 # usually between [0.1, 2]
  logical_batch_size: 128 # for physical of 64
