Network:
  physical_batch_size: 16
  lr: 2e-4
  amsgrad: False
  weight_decay: 0
  num_epochs: 80
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
checkpoint_name_best_loss: checkpoint_best_loss.tar
DP_checkpoint_name: DP_checkpoint.tar

# changeable items:
file_path: /PATH TO DATASET/
target_dir: /WHERE YOU WANT TO STORE YOUR EXPERIMENTS/
display_stats_freq: 1 # valid freq is equal to this

DP:
  epsilon: 4
  delta: 1e-5
  max_grad_norm: 1.5 # this has a direct relationship with controlling the sensitivity
  logical_batch_size: 128 # for physical of 64
